Numpy Workshop session

In [34]:
import numpy as np

print ([1,2,3])
n = np.array([1,2,3])
print (n)

print (type([1,2,3]))
print (type(n))

[1, 2, 3]
[1 2 3]
<class 'list'>
<class 'numpy.ndarray'>


In [37]:
# printing the dimension and shape of an nd  numpy
import numpy as np

n = np.array([[1,2,3],[4,5,6],[2,3,4]])
print ("Dimension of the numpy array---->",n.ndim)
print ("Shape of the numpy array---->",n.shape)
#print(n.shape[0])


Dimension of the numpy array----> 2
Shape of the numpy array----> (3, 3)


In [38]:
# range and arange 
import numpy as np
L=range(1000)
[x**2 for x in L]

L2=np.arange(1000)
L2**2


# In[35]:

get_ipython().magic(u'timeit [x**2 for x in L]')


# In[36]:

get_ipython().magic(u'timeit L2**2')

1000 loops, best of 3: 348 µs per loop
The slowest run took 14.89 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.63 µs per loop


In [5]:
from numpy.random import randn


# In[38]:

np.sin(randn(100))


# In[39]:

x= randn(10)
y= randn(10)
print(x,y)
print(np.maximum(x,y))


[ 2.06154253  1.39324911  0.11322659  1.19261048  0.36755914 -1.40209885
 -0.04182723  1.21656035  0.72114516  0.09795175] [-1.18604184 -1.98764914 -0.2467481   1.11320817 -0.58641922  0.08248916
  0.40539202  1.07370184  0.42753225 -0.23193332]
[ 2.06154253  1.39324911  0.11322659  1.19261048  0.36755914  0.08248916
  0.40539202  1.21656035  0.72114516  0.09795175]


In [7]:
import numpy as np
arr = np.arange(15).reshape((3,5))
print(arr)
print(arr.T)

print(np.dot(arr.T,arr))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[125 140 155 170 185]
 [140 158 176 194 212]
 [155 176 197 218 239]
 [170 194 218 242 266]
 [185 212 239 266 293]]


In [8]:
import numpy as np
arr= np.random.randn(5,4)
print(arr)

print(arr.mean())
print(arr.sum())

#r
print(arr.sum(axis=0)) 
print(arr.sum(axis=1))
print(arr.cumsum())


[[-0.34508069  1.75599937  0.26487167  0.9669333 ]
 [ 2.20022637 -0.02088213 -0.13679944  1.09675474]
 [-1.1412583  -0.93136896  2.07352539 -0.22419319]
 [-0.02660881 -0.4493576   1.65694726 -0.53563917]
 [-1.32785243 -0.62289117  0.76633336 -0.75782261]]
0.213091847757
4.26183695514
[-0.64057386 -0.26850049  4.62487824  0.54603306]
[ 2.64272365  3.13929954 -0.22329505  0.64534167 -1.94223285]
[-0.34508069  1.41091868  1.67579035  2.64272365  4.84295002  4.82206789
  4.68526845  5.78202319  4.64076489  3.70939593  5.78292132  5.55872814
  5.53211933  5.08276172  6.73970898  6.20406981  4.87621738  4.25332621
  5.01965957  4.26183696]


In [41]:
import numpy as np

A= np.array([1,1,1,1,1,3])


print(np.unique(A))

[1 3]


Linear Algebra in Numpy

In [10]:
from numpy.linalg import inv


x= np.random.randn(500,500)
print(x)

print(inv(x.T.dot(x)))

[[ 1.16383748 -1.4794961  -1.83669792 ...,  0.11029316  0.60073181
   0.26531879]
 [ 1.34157475 -0.04223407 -0.89037501 ..., -0.53900407  0.22955963
  -1.28797641]
 [-1.8137602   1.05122563 -0.02548042 ...,  0.72391247 -0.93202094
   1.01636989]
 ..., 
 [ 0.20254559 -0.23613691  0.53406835 ..., -1.19297362  0.20494097
   1.1824505 ]
 [-0.3084698  -1.2625703  -0.88173982 ..., -0.28394486  1.17656714
   1.18083553]
 [ 0.41693455  0.55068544  1.71910368 ..., -1.3407854  -0.67353009
  -0.28313285]]
[[  6.02033814  18.6949946    1.73986959 ...,  -0.3198642    4.25753147
    3.81273783]
 [ 18.6949946   64.85703144   5.99513787 ...,  -1.08443016  13.92213815
   13.01010183]
 [  1.73986959   5.99513787   2.16608179 ...,  -0.12074518   1.30876234
    1.37347109]
 ..., 
 [ -0.3198642   -1.08443016  -0.12074518 ...,   0.16690133  -0.2378764
   -0.22972828]
 [  4.25753147  13.92213815   1.30876234 ...,  -0.2378764    3.47266697
    2.67532165]
 [  3.81273783  13.01010183   1.37347109 ...,  -0.2297

Pandas Library

In [23]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

a=Series([11,9,20])
print (a.values)
print (a.index)
#https://pandas.pydata.org/pandas-docs/stable/indexing.html

a=Series([11,9,20], index=["a","b","c"])
print(a)


# In[52]:

print(a["b"])


# In[53]:

data={'ohio':234.8, 'Texas':456,"Oregan":789,"Utah":5000}
Series(data)


# In[54]:

a=Series([1,2,3,4],index=["a","b","c","d"])
a.reindex(["a","b","c","d","e"],fill_value=0)

print(a)

[11  9 20]
RangeIndex(start=0, stop=3, step=1)
[11  9 20]
9
[1 2 3 4]


In [43]:
# data frame in pandas
import numpy as np
import pandas as pd
from pandas import Series, DataFrame
data= {'states':["Ohio","Ohio","Ohio","Nevada","Nevada"],
       'year':[2000,2001,2002,2001,2002],
       'pop':[1.5,1.7,2.4,2.9,3.2]}




frame=DataFrame(data)
print(frame)
print("------head----------")


print (frame.head(2))
print("-------tail---------")
print (frame.tail(3))
print("-------add col---------")


# In[58]:

#frame["states"]
frame["debt"]=0
frame["debt"]=np.arange(5)
frame["debt"]=frame["states"]=="Ohio"
print(frame)
print("----------------")

data= DataFrame (np.random.randn(16).reshape((4,4)), 
                index=["Ohio","Utah","Texas","NY"],
                columns=['one','two','three','four'])

#olumns=['one','two','three','four']
#olumns.sort()
#rint(columns)
print("----------------")

print(data)
print("------Sort on axis----------")
# sort on axis 1
data=data.sort_index(axis=1)
print(data)
print("------print with condition----------")

print (data[data["three"]>0.05] )
print("-------change values in the series---------")
data[data<0.05]=0
print(data)
print("-------printing labels---------")
print(data.ix['Ohio',['one','two']])
print("--------apply function--------")

data.apply(sum,axis=0)
print(data)
print("--------apply function lambda--------")
data.apply(lambda x: x.max()-x.min(),axis=0)
print(data)
print("----------iloc-integer based location ----")
print(data.iloc[:,2])
print(data.iloc[:,1:3])
print(data.iloc[1:3,1:3])
print(data.iloc[1:3,])

print("------add labels-----")
data["Label"]=["a","b","b","a"]
print(data)

print("----------query and group by---")
print(data.groupby("Label")["two"].sum())

print(data.groupby(["Label","three"])["two"].sum())


# In[81]:
print("---------query----")

print(data.query(' Label=="a" '))
print(data.query(' Label=="a" and one >0.5'))

print("----split into groups---")
#Splitting an object into groups
df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
                              'foo', 'bar', 'foo', 'foo'],
                       'B' : ['one', 'one', 'two', 'three',
                              'two', 'two', 'one', 'three'],
                       'C' : np.random.randn(8),
                       'D' : np.random.randn(8)})
print(df)
print("----split into groups---")
grouped = df.groupby('A')
print(grouped)
print("----split into groups by lists---")
grouped = df.groupby(['A', 'B'])
print(grouped)

def get_letter_type(letter):
        if letter.lower() in 'aeiou':
            return 'vowel'
        else:
            return 'consonant'
print("----split into groups by function---")
grouped = df.groupby(get_letter_type, axis=1)
print(grouped)
for name, group in grouped:
           print(name)
           print(group)

   pop  states  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  2.4    Ohio  2002
3  2.9  Nevada  2001
4  3.2  Nevada  2002
------head----------
   pop states  year
0  1.5   Ohio  2000
1  1.7   Ohio  2001
-------tail---------
   pop  states  year
2  2.4    Ohio  2002
3  2.9  Nevada  2001
4  3.2  Nevada  2002
-------add col---------
   pop  states  year   debt
0  1.5    Ohio  2000   True
1  1.7    Ohio  2001   True
2  2.4    Ohio  2002   True
3  2.9  Nevada  2001  False
4  3.2  Nevada  2002  False
----------------
----------------
            one       two     three      four
Ohio   1.051710 -0.199102 -2.509394 -0.126583
Utah   0.481183 -1.717772  1.071980 -1.693308
Texas -0.445431 -0.471541 -0.847347  0.761684
NY    -0.185022  0.258978  0.975294  0.524935
------Sort on axis----------
           four       one     three       two
Ohio  -0.126583  1.051710 -2.509394 -0.199102
Utah  -1.693308  0.481183  1.071980 -1.717772
Texas  0.761684 -0.445431 -0.847347 -0.471541
NY     0.524935 -0.